#!/bin/bash
OUTPUT_PLUGINS=("prometheus_client")
INPUT_PLUGINS=("varnish" "cpu" "net" "mem" "disk" "diskio")

echo "Slimming down telegraf"

all_inputs="./plugins/inputs/all/all.go"
all_outputs="./plugins/outputs/all/all.go"
all_proc="./plugins/processors/all/all.go"
all_agg="./plugins/aggregators/all/all.go"


# OUTPUT
cat << EOF > ${all_outputs}
// Code generated by telegraf-slim
package all

import (
EOF

for plugin in ${OUTPUT_PLUGINS[@]}; do
	echo "_ \"github.com/influxdata/telegraf/plugins/outputs/${plugin}\"" >> ${all_outputs}
done
echo ")" >> ${all_outputs}

# INPUT
cat << EOF > ${all_inputs}
// Code generated by telegraf-slim
package all

import (
EOF

for plugin in ${INPUT_PLUGINS[@]}; do
	echo "_ \"github.com/influxdata/telegraf/plugins/inputs/${plugin}\"" >> ${all_inputs}
done
echo ")" >> ${all_inputs}

# ALL
cat << EOF > ${all_proc}
// Code generated by telegraf-slim
package all

import (
)
EOF

cat << EOF > ${all_agg}
// Code generated by telegraf-slim
package all

import (
)
EOF


